// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:ddaf4d08-7d68-4ff7-bdec-4b2f8099ca34",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_UzLU0lXMD",
    "aws_user_pools_web_client_id": "7jiek61i29fqg75gdl167nr0ae"
};


export default awsmobile;
